// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppilcationPreview: typeof import('./src/components/MainModals/ApplicationViews/AppilcationPreview.vue')['default']
    ApplicationEdit: typeof import('./src/components/MainModals/ApplicationViews/ApplicationEdit.vue')['default']
    ApplicationForm: typeof import('./src/components/MainModals/ApplicationViews/ApplicationForm.vue')['default']
    ApplicationList: typeof import('./src/components/MainModals/ApplicationViews/ApplicationList.vue')['default']
    AvatarInput: typeof import('./src/components/MenuModals/AvatarInput.vue')['default']
    BottomCard: typeof import('./src/components/MenuModals/BottomCard.vue')['default']
    CalendarEdit: typeof import('./src/components/MainModals/CalendarViews/CalendarEdit.vue')['default']
    CalendarForm: typeof import('./src/components/MainModals/CalendarViews/CalendarForm.vue')['default']
    CalendarList: typeof import('./src/components/MainModals/CalendarViews/CalendarList.vue')['default']
    CropModal: typeof import('./src/components/MenuModals/CropModal.vue')['default']
    CropperItem: typeof import('./src/components/MenuModals/CropperItem.vue')['default']
    EditTextModal: typeof import('./src/components/MenuModals/EditTextModal.vue')['default']
    EducationEdit: typeof import('./src/components/MainModals/EducationViews/EducationEdit.vue')['default']
    EducationForm: typeof import('./src/components/MainModals/EducationViews/EducationForm.vue')['default']
    EducationList: typeof import('./src/components/MainModals/EducationViews/EducationList.vue')['default']
    ExperienceEdit: typeof import('./src/components/MainModals/ExperienceViews/ExperienceEdit.vue')['default']
    ExperienceForm: typeof import('./src/components/MainModals/ExperienceViews/ExperienceForm.vue')['default']
    ExperienceList: typeof import('./src/components/MainModals/ExperienceViews/ExperienceList.vue')['default']
    IconProfile: typeof import('./src/components/MenuModals/IconProfile.vue')['default']
    KnowledgeEdit: typeof import('./src/components/MainModals/KnowledgeViews/KnowledgeEdit.vue')['default']
    KnowledgeForm: typeof import('./src/components/MainModals/KnowledgeViews/KnowledgeForm.vue')['default']
    KnowledgeList: typeof import('./src/components/MainModals/KnowledgeViews/KnowledgeList.vue')['default']
    MenuBar: typeof import('./src/components/MenuModals/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/MenuModals/MenuItem.vue')['default']
    MotivationEdit: typeof import('./src/components/MainModals/MotivationViews/MotivationEdit.vue')['default']
    MVEditModal: typeof import('./src/components/MenuModals/MVEditModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperCard: typeof import('./src/components/MenuModals/SwiperCard.vue')['default']
    Tiptap: typeof import('./src/components/TipTapModals/Tiptap.vue')['default']
    UserForm: typeof import('./src/components/MainModals/UserInfoViews/UserForm.vue')['default']
    UserInfoDisplay: typeof import('./src/components/MainModals/UserInfoViews/UserInfoDisplay.vue')['default']
    UserInfoEdit: typeof import('./src/components/MainModals/UserInfoViews/UserInfoEdit.vue')['default']
  }
}
