// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarInput: typeof import('./src/components/AvatarInput.vue')['default']
    BottomCard: typeof import('./src/components/BottomCard.vue')['default']
    CropModal: typeof import('./src/components/Modals/CropModal.vue')['default']
    CropperItem: typeof import('./src/components/CropperItem.vue')['default']
    CustomCalendar: typeof import('./src/components/CustomCalendar.vue')['default']
    EditTextModal: typeof import('./src/components/Modals/EditTextModal.vue')['default']
    IconProfile: typeof import('./src/components/IconProfile.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    MVEditModal: typeof import('./src/components/Modals/MVEditModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperCard: typeof import('./src/components/SwiperCard.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap.vue')['default']
  }
}
